### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by mkoennecke** [ess-dmsc/python-nexus-utilities#11]
I tried to run  example_instruments/sans2d/SANS2D_example.py and came back on me with missing the file sans_test.nxs. Which does not exist in the repository. Can you please add the file.

I another matter: in order to run this I had to set the PYTHONPATH to include the root directory 
of python-nexus-utilities. Otherwise it would not find nexusbuilder etc. Pleas update the docs.

**Comment by matthew-d-jones** [comment]
Sorry @mkoennecke. The example script should be run from its own directory, that is why the nxs file was not found. Also, as you say, the repository root must be in `PYTHONPATH`. I didn't come across that problem as my IDE does that automatically.

For now I've updated the instructions in the README. A better solution might be to move the example scripts and files to a separate repository and import this one as a submodule or add a setup file and use `pip -e`. I'll leave this issue open until I've done something about that.
