### ISSUE TITLE
NeXus Shape Structure

### ISSUE THREAD

**Issue by mkoennecke** [ess-dmsc/python-nexus-utilities#12]
I now had a good look at the resulting NeXus file and ist structure. Lacking (or not finding) any documentation  on this required some guess work from me. So, all I am writing below is under the condition that I may have guessed wrong. 

I now concentrate on the description of the detector shape because that is the new thing to discuss regarding NeXus. 

The path I am now discussing is raw_data_1/instrument/detector_1/left_tubes/pixel_shape

This only makes sense to me if I assume that vertices is an array of coordinates relative to some detector coordinate system. Then the faces array describes the rectangles  which make up the geometrical model of the detector. This array contains indices into the vertices array. This looks good to me; I just wonder why rectangles are used. Normally in computer graphics everything is done with triangles. I am also not sure if NXshape is the right NeXus class for this. This is something new to NeXus and may require a new name, for example NXsolid_geometry. To be discussed with the NIAC.

Now, this whole lot needs to be placed relative to the origin of the instrument. According to the description of sans2d on the WWW  there is a translation along the beam (distance) and sideways. Sideways would be an x-translation in McStas coordinates. So, what IMHO is needed is a NXtransformations group holding these two translations. Then depends_on chain then looks like:
     x_translation -- distance -- .

The current depends_on in detector_1 is currently pointing to a sample translation. This looks decidedly wrong to me. 

Now what at this point is still not clear is which detector pixel is described by which faces in the faces array.  I think the NXgrid_pattern group is attempting to describe that but without documentation its usage eludes me. I, personally, would do away with the group and have a mapping array: face_mapping[ndet,nfaces+1] which would contain a mapping of the detector_id to the face id's in the faces array describing that detector element. Here is a potential problem: in the example the detector elements appear to be described by boxes. If we have other shapes or a mix of shapes the nfaces dimension may become ragged. There may be other mapping options.

Anyway, the whole thing belongs in front of the NIAC. The NIAC representative for ISIS is Freddie Akeroyd.

**Comment by matthew-d-jones** [comment]
@mkoennecke thanks for the feedback. The documentation is on the wiki page I gave you a link for in the email, it addresses most of the questions/concerns you've raised.

**Comment by matthew-d-jones** [comment]
Continuing discussion on the wiki
