### ISSUE TITLE
Create NeXus features for some proportion of the information stored in the examples 

### ISSUE THREAD

**Issue by zjttoefs** [ess-dmsc/python-nexus-utilities#43]
And flag compliance

**Comment by matthew-d-jones** [comment]
For example find the sample env value in NXlog closest to the timestamp of a particular neutron detection.

**Comment by matthew-d-jones** [comment]
https://github.com/nexusformat/features/pull/10
https://github.com/nexusformat/features/pull/7
https://github.com/nexusformat/features/pull/31

and `features` dataset is added to generated files.
